#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-FastCGI
version:      0.1
version_from: lib/POE/Component/FastCGI.pm
installdirs:  site
requires:
    HTTP::Request:                 0
    CGI::Util:                     0
    HTTP::Response:                0
    POE:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
