--- #YAML:1.0
name:               POE-Component-FastCGI
version:            0.11
abstract:           POE FastCGI server
author:
    - David Leadbeater <cpan@dgl.cx>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::Util:       0
    HTTP::Request:   0
    HTTP::Response:  0
    POE:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
